-- hs.window.switcher.ui.textColor = {0.9,0.9,0.9}
-- hs.window.switcher.ui.fontName = 'Lucida Grande'
-- hs.window.switcher.ui.textSize = 15
-- hs.window.switcher.ui.highlightColor = {0.8,0.5,0,0.6} 
-- hs.window.switcher.ui.backgroundColor = {0.3,0.3,0.3,0.6}
-- hs.window.switcher.ui.onlyActiveApplication = true
-- hs.window.switcher.ui.showTitles = false
-- hs.window.switcher.ui.titleBackgroundColor = {0,0,0}
-- hs.window.switcher.ui.showThumbnails = true 
-- hs.window.switcher.ui.thumbnailSize = 200
-- hs.window.switcher.ui.showSelectedThumbnail = false
-- hs.window.switcher.ui.selectedThumbnailSize = 150

-- local switcher = hs.window.switcher.new()
-- hs.hotkey.bind({'alt'}, 'tab', function() switcher:next() end)